### PR TITLE
Type Contracts Added

### PR DESCRIPTION
**Pull request by CubeUlations**
I have added Type Contracts for the following files making the
readibility of the code easier espicially for the large classes. Just a
fellow coder helping one another!

### CODE REVIEW

**Comment by CubeUlations** [comment]
I may come back to this project and do more documentation work but in the meantime this is all the time i had today. Good Luck with your project!

**Comment by jonathanslenders** [comment]
Hi @CubeUlations,

Thanks for the pull request! I really appreciate the effort, but I can't merge this.

The reason is that these contracts are not adding any value to the code. All information in these contracts can be deducted through type inference. (Jedi and editors like PyCharm know how.) It's basically duplicating what the function signature is already saying.  Did you maybe use a tool to generate these type contracts?

If however, we want to add type documentation, then I strongly prefer the Sphinx way of doing it.
I hope you understand the reasoning.

Jonathan

**Comment by CubeUlations** [comment]
Hey @jonathanslenders ,

No problem ill take that into consideration as i help others as well. I think type contracts are essential to all code as it really helps with the readability of the functions as well as the consistency of proper documentation. Although PEP-8 doesn't focus on it, it usually is necessary but no worries!. Also i did not auto generate them, I kind of did them by hand XD. Ill look into Sphinx's way thanks for the info!

P.S Kind of new to whole GitHub thing but i'm so happy you replied in a nice understanding way <3

**Comment by jonathanslenders** [comment]
You're welcome! I appreciate the effort you did.
Anyway, good luck with all projects you're going to work on.

**Pull request closed without merging**
